import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins', // Ensure this is applied consistently
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans`}>
        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
